name: yolox

channels:
- conda-forge

dependencies:
- pytorch>=1.7
- loguru
- tqdm
- torchvision
- ninja
- tabulate
- psutil
- tensorboard

# verified versions
# pycocotools corresponds to https://github.com/ppwwyyxx/cocoapi
- pycocotools>=2.0.2
- onnx>=1.13.0
- pip:
  - onnx-simplifier #==0.4.10
  - thop

- opencv

- ipykernel
