# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: thesis

channels:
- conda-forge

dependencies:
- python
- ruamel.yaml  # for envy

- ipykernel
- papermill

- numpy
- matplotlib
- scikit-image
