#!zsh

echo Run this on you local machine to start a remote code tunnel server to connect with from your local vscode UI.

ssh uthpc <<'EOF'
if ! type code > /dev/null; then    # install vscode cli if not present
  curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' |\
  tar -xz -C ~/.local/bin
fi

cd thesis
./gpu

code tunnel --accept-server-license-terms
EOF
