#!bash

# needs  micromamba activate thesis && ./gpu

OUTDIR=result

cd "$(dirname "$1")"
mkdir "$OUTDIR" 2>/dev/null || true

papermill "$(basename "$1")" "$OUTDIR/$(basename "$1" .ipynb).$(date +%y%m%d-%H%M%S).ipynb"
