name: cellpose
channels:
- conda-forge
dependencies:
- python=3.8
- cellpose[gui]

- matplotlib  # for plots
- ipykernel  # for notebooks

- scikit-image   # for segmentation plots (color.label2rgb) and image reading and to grayscale
