name: cellpose
channels:
- conda-forge
dependencies:
- cellpose

- matplotlib  # for plots
- ipykernel  # for notebooks
- jupytext
- nbconvert

- scikit-image
- colorcet
- pandas
- pip:
  - onnxruntime-gpu 
  - onnxruntime