name: classic
channels:
- conda-forge

dependencies:

- ipykernel
- nbconvert
- jupytext

- numpy
- pandas
- matplotlib
- colorcet
- seaborn
- scikit-learn
- scikit-image
- scipy
- opencv
- colour-science

- holoviews
- jupyter_bokeh

- onnxruntime
- pip:
  - onnxruntime-gpu 