name: classic
channels:
- conda-forge

dependencies:
- python==3.11

- ipykernel
- nbconvert
- jupytext

- numpy
- pandas
- matplotlib
- colorcet
- seaborn
- scikit-learn
- scikit-image
- scipy
- opencv
- colour-science