name: micro-sam
channels:
- conda-forge
dependencies:
- micro_sam  # lib
- napari  # annotate
- pyqt  # annotate
- torch_em  # train

- matplotlib  # for plots
- ipykernel  # for notebooks

- scikit-image  # for blob-detectio