name: seunet
channels:
- conda-forge
dependencies:
- albumentations
- einops
- fvcore
- iopath
- ipython
- matplotlib
- numpy
- pandas
- pip
- pycocotools
- pytorch
- scikit-image
- scikit-learn
- scipy
- tifffile
- timm
- torchvision
- tqdm
- typing_extensions
- pip:
  - opencv-python
  - opencv-python-headless
