name: area
channels:
- conda-forge
dependencies:

- jupytext
- ipykernel  
- nbconvert

- onnxruntime
- pip:
  - onnxruntime-gpu 

- matplotlib 
- scikit-image
- colorcet
- pandas
  
- holoviews
- jupyter_bokeh
- bokeh
